@baseurl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}


# @name validate_token 
GET {{baseurl}}/validate-token
Content-Type: application/json                        
Authorization: 'Bearer {{{{authToken}}}}'

###

# @name create_account
POST {{baseurl}}/accounts
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@gmail.com",
  "password": "12345678"
}



###

# @name authenticate 
POST {{baseurl}}/sessions
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "12345678"
}

###

# @name create_therapeutic_class 
POST {{baseurl}}/therapeutic-class
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "antibiótico"
}
