version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pharma-db
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - pharma-net

  api:
    build: .
    container_name: pharma-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - pharma-net
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/src/infra/main.js
      "

volumes:
  postgres_data:

networks:
  pharma-net:
    driver: bridge
