services:
  postgres:
    container_name: pharma
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pharma
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/bitnami/postgresql
    
  app:
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
    build: .
    container_name: pharma-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres