version: "3.8"

services:
  postgres:
    container_name: pharma-db
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/bitnami/postgresql

  app:
    build: .
    container_name: pharma-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "
        npm run test &&
        npm run test:e2e &&
        npx prisma migrate deploy &&
        npm run start:prod
      "